[package]
edition = "2018"
exclude = ["index.node"]
license = "ISC"
name = "my-neon-project"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
default-features = false
features = ["napi-6"]
version = "0.8"

[dependencies]
chrono = "0.4"
